### ISSUE TITLE
LC1C tool uses between 60% and 70% CPU

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-local-chain#4] opened 2023-11-07 12:40 UTC
**Bug Description**
After starting a local chain, the tool uses between 60% and 70% of CPU, occasionally spikes to over 100%.

**Steps to Reproduce**

1. Stat the tool.
2. Look at the lc1c monitoring (Concordium Explorer)
3. Look at the CPU consumption

**Expected Result**
The application should not use 60% of the CPU.

**Actual Result**
Consumption is between 60% and 70%, sometimes spikes over 100%.

Also, consumption is over 60% even if one doesn't switch through tabs.

**Versions**
- Software Version: 0.1.0
- OS: Ubuntu 22.04.3 LTS

**PC Specs**
Lenovo ThinkPad X1 Carbon 7th 
Intel® Core™ i7-8565U CPU @ 1.80GHz × 8 
6 GB RAM

**Comment by gachouchani1999** [comment] 2023-11-12 20:46
This is a weird issue that we were not able to reproduce on 2 different OS. Please @mh-concordium try the latest version in the PR and let us know if you still face a similar issue.

**Comment by mh-concordium** [comment] 2023-11-14 08:37
Here is the usage on MacOS after approximately 5 minutes of running. Version 0.1.1
<img width="1435" alt="image" src="https://github.com/Concordium/concordium-local-chain/assets/98821384/4dc49672-54e0-4879-b2ee-c4209a9a305e">

**Comment by lucifer1708** [comment] 2023-11-14 17:54
Hey @mh-concordium !
Are encountering this high cpu usage on this stage?
![282874301-74a7f1ad-d7b9-4f0e-ac00-44994498b73a (1)](https://github.com/Concordium/concordium-local-chain/assets/76207887/69f621cb-bcf3-41e1-8f12-09f793ddb656)

otherwise it is using 9-10% cpu in my system on this dashboard.
![282874628-e7bb70f5-e685-4ed6-9f18-3f8e66a2ce38 (1)](https://github.com/Concordium/concordium-local-chain/assets/76207887/1ce18e04-8c0e-4b8a-a7c2-8416e80214d8)

I monitored it throughout the process but only able to see the cpu usage peak when cargo was installing the genesis-creator binary.

System Specs:
 - Asus Tuf A15
 - Ryzen 5 4600H
 - 16 Gigs RAM

**Comment by mh-concordium** [comment] 2023-11-15 06:53
Here I have uploaded a video of the appearence.

[Screencast from 11-15-2023 07:51:08 AM.webm](https://github.com/Concordium/concordium-local-chain/assets/98821384/90e90808-2a6e-4924-81e3-3554878d5251)

**Comment by abizjak** [comment] 2024-01-21 19:23
This is probably fixed with the general improvement in resource consumption.

There are still cases where resource use might be high in case of a lot of accounts and a lot of transactions being sent on the chain.

**Comment by lucifer1708** [comment] 2024-01-22 03:33
Let me see if the consumption is due to concordium node or the lc1c.

**Comment by abizjak** [comment] 2024-01-22 08:52
I don't think there's anything for you to do at the moment.

**Comment by EmilLa1** [comment] 2024-02-16 05:35
Fixed via https://github.com/Concordium/concordium-local-chain/pull/27

**Closed by EmilLa1** 2024-02-16 05:35 UTC
Labels: [Prio] High, [Type] Bug
